language: node_js
node_js:
  - "7.4.0"
cache: 
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
    - rm -f $HOME/.meteor/log/*.log

services:
  - docker

before_install:
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
  - npm i -g reaction-cli coveralls
  - meteor npm install

script: 
  - reaction test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info