language: node_js

node_js:
  - "7.4.0"

services:
  - docker

before_script:
  - sleep 15
  - if [[ -L ~/.meteor/meteor ]]; then ln -s ~/.meteor/meteor ~/bin/meteor; export PATH="$PATH:~/bin"; fi
  - hash meteor 2>/dev/null || curl https://install.meteor.com | /bin/sh
  - npm i -g reaction-cli
  - meteor npm install

before_install:
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script: reaction test

after_script:
- cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js