language: node_js
node_js:
  - "7.4.0"
cache: 
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
    - rm -f $HOME/.meteor/log/*.log

services:
  - docker

before_install:
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
  - npm i -g reaction-cli coveralls
  - meteor npm install

script: 
  - mkdir .coverage
  - reaction test
  - cat .coverage/lcov.info | coveralls || cat .coverage/lcov.info || true
